language: node_js

node_js:
- "node"

#addons:
#    apt:
#        packages:
#        - xvfb
#
#install:
#- export DISPLAY=':99.0'
#- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache:
    directories:
    - node_modules

install:
- npm install

script:
#- npm run lint
#- npm test
- npm run compile
- npm run build

deploy:
    provider: releases
    api_key: 9fe73b6d02afe74e423b52192422fe2edf06fcaa
    file: dist/stacker-0.1.0-mac.zip
    skip_cleanup: true
    on:
        tags: true


