language: node_js

node_js:
  - node

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm run lint
  - npm run test:unit
